name: ISA autotests
run-name: Testing ${{ github.repository }} by @${{ github.actor }}

on:
  create:
  repository_dispatch: 
  workflow_dispatch: 

jobs:
  run-tests:
    with:
      student_url: ${{ github.repository }}
      student_ref: ${{ github.sha }}
    uses: skkv-se-comp-arch/private-tools-26/.github/workflows/isa.yml@main
    secrets: inherit
